### ISSUE TITLE
target[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by UziTech** [morassman/process-palette#55]
[Enter steps to reproduce:]

1. Open Atom v 1.23.0-beta

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [process-palette](https://github.com/morassman/process-palette) package 0.15.2

### Stack Trace

Failed to activate the process-palette package

```
At target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/tooltip-manager.js:117:35)
    at MainView.module.exports.MainView.initialize (/packages/process-palette/lib/views/main-view.coffee:33:36)
    at /packages/process-palette/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/process-palette/lib/views/main-view.coffee:12:5)
    at Object.activate (/packages/process-palette/lib/main.coffee:36:21)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:647:50)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode undefined 
atom-beautify 0.30.6 
atom-ide-ui 0.5.4 
atom-jasmine 0.8.1 
atom-minify 0.8.0 
atom-typescript 11.0.10 
atomic-chrome 0.3.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.0 
change-case 0.6.5 
chrome-color-picker 0.8.0 
code-peek 1.4.21 
context-git 0.17.6 
context-menu-remove 0.1.0 
cson 2.0.1 
cursor-history 0.12.0 
dbclick-tree-view 1.6.3 
docblockr 0.13.2 
double-tag 1.1.0 
editor-stats 0.17.0 
editorconfig 2.2.2 
emmet 2.4.3 
external-open 0.6.3 
file-icons 2.1.13 
file-types 0.5.5 
file-watcher 1.2.6 
flex-tool-bar 0.12.0 
git-time-machine 1.5.9 
grammar-token-limit 0.1.1 
highlight-selected 0.13.1 
hyperclick 0.0.0 
hyperclick-php 0.2.1 
hyperlink-hyperclick 1.3.4 
ide-php 0.6.9 
ide-typescript 0.6.2 
intentions 1.1.5 
js-hyperclick 1.12.1 
keybinding-cheatsheet 0.1.1 
language-babel 2.77.3 
language-batch 0.4.0 
language-htaccess 0.1.1 
language-ini 1.19.0 
language-vbscript 0.9.0 
line-diff-details 1.9.0 
line-ending-converter 1.3.2 
linter-coffeelint 1.3.1 
linter-eslint 8.4.0 
linter-htmlhint 1.4.0 
linter-js-yaml 1.2.8 
linter-markdown 5.2.0 
linter-phpcs 1.6.8 
linter-sass-lint 1.8.3 
linter-twig 0.4.2 
linter-write-good 0.9.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
my-settings-view 0.252.2 
node-debugger 1.10.1 
notifications-plus 0.69.11 
notifications-plus-confetti 0.1.4 
npm-install 4.0.4 
open 0.0.5 
open_in_cmd 0.6.1 
open-in-developer-mode 0.3.0 
php-debug 0.2.5 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-twig 4.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
process-palette 0.15.2 
project-manager 3.3.5 
react 0.16.3 
Remote-FTP 1.3.1 
rest-client 1.3.1 
sass-autocompile 0.13.3 
script undefined 
scroll-editor-on-middle-click 0.4.0 
scroll-sync 0.2.3 
sort-lines 0.18.0 
split-diff 1.5.1 
Sublime-Style-Column-Selection 1.7.4 
tabs-to-spaces 1.0.3 
text-manipulation 0.6.0 
todo-show 2.1.0 
tool-bar 1.1.0 
trailing-semicolon 1.1.0 
trailing-spaces 0.4.0 
transpile 0.1.4 
transpile-decaf 0.1.3 
tree-view-git-status 1.4.0 
uzitech-toggle-quotes 0.0.0 
vic 0.0.0 
wakatime 7.0.3 
web-accessibility-checker 0.1.4 
Zen 0.18.0 
```

**Comment by UziTech** [comment]
This seems to be an issue with Atom 1.23.0 adding tooltips to an element from `atom-space-pen-view`

**Comment by UziTech** [comment]
same issue https://github.com/platformio/platformio-atom-ide-terminal/issues/403

**Comment by alflanagan** [comment]
Occurring in Linux also -- Fedora 26.

**Comment by UziTech** [comment]
this is fixed in https://github.com/atom/atom/pull/16144
