### ISSUE TITLE
Failed to activate the process-palette package

### ISSUE THREAD

**Issue by steventango** [morassman/process-palette#58]
[Enter steps to reproduce:]

1. Open Atom

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [process-palette](https://github.com/morassman/process-palette) package 0.15.2

### Stack Trace

Failed to activate the process-palette package

```
At target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/tooltip-manager.js:117:35)
    at MainView.module.exports.MainView.initialize (/packages/process-palette/lib/views/main-view.coffee:33:36)
    at /packages/atom-minify/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/process-palette/lib/views/main-view.coffee:12:5)
    at Object.activate (/packages/process-palette/lib/main.coffee:36:21)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/package-manager.js:647:50)
    at ~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/atom-environment.js:865:36
```

### Commands

```
     -0:06.9.0 editor:consolidate-selections (input.hidden-input)
     -0:06.9.0 atom-minify:close-panel (input.hidden-input)
     -0:06.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-minify 0.8.0 
autocomplete-paths 2.12.1 
busy 0.7.0 
busy-signal 1.4.3 
chrome-color-picker 0.8.0 
emmet 2.4.3 
file-icons 2.1.13 
intentions 1.1.5 
language-batch 0.4.0 
language-powershell 4.0.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
pigments 0.40.2 
process-palette 0.15.2 
sass-autocompile 0.13.3 
sort-lines 0.18.0 
toggle-quotes 1.0.1 
wakatime 7.0.4 
```

**Comment by morassman** [comment]
This is an [issue](https://github.com/atom/atom/pull/16144) with the beta release, but should be fixed in the next release.
