### ISSUE TITLE
Failed to load the process-palette package

### ISSUE THREAD

**Issue by wade0518** [morassman/process-palette#85]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [process-palette](https://github.com/morassman/process-palette) package 0.17.0

### Stack Trace

Failed to load the process-palette package

```
At Cannot find module 'C:\Users\kencw\.atom\packages\process-palette\node_modules\underscore-plus\lib\underscore-plus.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\kencw\.atom\packages\process-palette\node_modules\underscore-plus\lib\underscore-plus.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/process-palette/lib/main.coffee:1:5)
    at /packages/process-palette/lib/main.coffee:1:1)
    at /packages/process-palette/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3670531)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3657071
    at Package.measure (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3655871)
    at Package.load (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3656644)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:382220)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:380643
    at Config.transact (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:332606)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:380581)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:744229
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:746268)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.13.1 
build 0.70.0 
build-arduino 0.1.1 
busy-signal 2.0.1 
file-icons 2.1.46 
ide-c-cpp 0.1.0 
intentions 1.1.5 
keyboard-neo2 1.0.0 
language-ini 1.23.0 
linter 3.3.0 
linter-gcc2 0.8.8 
linter-ui-default 3.2.2 
platformio-aia 0.0.5 
platformio-ide 2.7.2 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.1 
process-palette 0.17.0 
tool-bar 1.4.2 
```

**Comment by morassman** [comment]
I'm not sure why this happened. It might be that process-palette didn't install properly for whatever reason. There has been a new version released in the mean time. Please install it and let me know if you still get this issue.
