### ISSUE TITLE
Uncaught Error: Invalid child node: undefined

### ISSUE THREAD

**Issue by cornelius-dol** [morassman/process-palette#99]
[Enter steps to reproduce:]

1. Launch a previously working process.

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: Windows 10, X64, Fully up to date.
**Thrown From**: [process-palette](https://github.com/morassman/process-palette) package 0.19.3

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At c:\data\lawrence\setting\.atom\packages\process-palette\node_modules\etch\lib\dom.js:33

Error: Invalid child node: undefined
    at Object.dom (/packages/process-palette/node_modules/etch/lib/dom.js:33:15)
    at PIDButtonView.render (/packages/process-palette/lib/views/pid-button-view.js:24:7)
    at Object.initialize (/packages/process-palette/node_modules/etch/lib/component-helpers.js:42:31)
    at PIDButtonView.initialize (/packages/process-palette/lib/views/view.js:22:10)
    at PIDButtonView.initialize (/packages/process-palette/lib/views/pid-button-view.js:8:35)
    at /packages/process-palette/lib/views/pid-button-view.js:18:10)
    at PIDButtonsView.addButton (/packages/process-palette/lib/views/pid-buttons-view.js:56:24)
    at PIDButtonsView.processStarted (/packages/process-palette/lib/views/pid-buttons-view.js:52:10)
    at /packages/sync-settings/node_modules/underscore/underscore-umd.js:1451:47
    at map (/packages/sync-settings/node_modules/underscore/underscore-umd.js:1349:24)
    at /packages/sync-settings/node_modules/underscore/underscore-umd.js:1442:12)
    at Object.invoke (/packages/sync-settings/node_modules/underscore/underscore-umd.js:76:29)
    at ConfigController.notifyProcessStarted (/packages/process-palette/lib/controllers/config-controller.js:336:7)
    at ProcessController.processStarted (/packages/process-palette/lib/controllers/process-controller.js:723:27)
    at ProcessController.runProcessAfterProjectInput (/packages/process-palette/lib/controllers/process-controller.js:635:10)
    at ProcessController.runProcessAfterUserInput (/packages/process-palette/lib/controllers/process-controller.js:515:12)
    at ProcessController.takeUserInput (/packages/process-palette/lib/controllers/process-controller.js:497:12)
    at ProcessController.runProcessAfterSave (/packages/process-palette/lib/controllers/process-controller.js:492:10)
    at ProcessController.saveEditors (/packages/process-palette/lib/controllers/process-controller.js:450:12)
    at ProcessController.saveDirtyFiles (/packages/process-palette/lib/controllers/process-controller.js:382:12)
    at ProcessController.runProcessWithFile (/packages/process-palette/lib/controllers/process-controller.js:373:10)
    at ConfigController.runProcessWithFile (/packages/process-palette/lib/controllers/config-controller.js:229:23)
    at ConfigController.runProcess (/packages/process-palette/lib/controllers/config-controller.js:213:10)
    at /packages/process-palette/lib/controllers/config-controller.js:27:109)
    at CommandRegistry.handleCommandEvent (D:/lawrence/setting/windows/appdata/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:352663)
    at KeymapManager.dispatchCommandEvent (D:/lawrence/setting/windows/appdata/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:1228249)
    at KeymapManager.handleKeyboardEvent (D:/lawrence/setting/windows/appdata/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:1224383)
    at WindowEventHandler.handleDocumentKeyEvent (D:/lawrence/setting/windows/appdata/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -0:09.2.0 process-palette:create-file (input.hidden-input)
```

### Non-Core Packages

```
autosave-onchange 1.5.1 
block-comment 0.4.3 
ctrl-dir-scroll 0.2.5 
custom-window-title 1.0.4 
grammar-token-limit 0.1.1 
justright-latte-syntax 0.1.0 
justright-latte-ui 0.1.0 
just-right-ui 0.2.0 
language-batchfile 0.7.7 
language-ini 1.25.0 
magic-reflow 0.3.0 
multi-cursor-plus 1.2.0 
overtype-ii 1.0.0 
process-palette 0.19.3 
project-manager 3.3.8 
sort-lines 0.19.0 
sync-settings 5.2.15 
tree-view-sort 0.12.1 
```

**Comment by cornelius-dol** [comment]
This was a screw up in my environment settings, resulting in an invalid path for `command.exe`
